"""empty message

Revision ID: 740f97b22eb3
Revises: 5f9ae7c7f4a2
Create Date: 2025-12-11 12:46:22.593105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740f97b22eb3'
down_revision = '5f9ae7c7f4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=50), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload')
    # ### end Alembic commands ###
